theme = "nord"

[editor]
line-number = "relative"
bufferline = "multiple"
color-modes = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = ["mode", "file-name", "file-modification-indicator", "position", "position-percentage"]
right = ["diagnostics", "version-control", "file-type"]

[editor.indent-guides]
render = true

[editor.whitespace.render]
space = "all"

